projectname: "avesha"
workspaces:
  - name: "workspace-a"
    namespaces: 
      - "namespace-a2"
      - "namespace-a1"
    username: "admin-1"
    email: "admin1@acme.io"
    clusters:
      - "worker-1"
      # - "worker-2"