
projectname: "avesha"
workspaces:
  - name: "workspace-g"
    namespaces: 
      - "namespace-g2"
      - "namespace-g1"
    username: "workspace-"
    email: "admin1@acme.io"
    clusters:
      - "worker-1"
      # - "worker-2"
    apiKeyValidity: "2025-12-31"
