projectname: "avesha"
workspaces:
  - name: "workspace-b"
    namespaces: 
      - "namespace-b2"
      - "namespace-b1"
    username: "admin-1"
    email: "admin1@acme.io"
    clusters:
      - "worker-1"
      # - "worker-2"
    apiKeyValidity: "2025-12-31" # apiKeyValidity
