projectname: "avesha"
workspaces:
  - name: "workspace-2r"
    namespaces: 
      - "namespace-2r2"
      - "namespace-2r1"
    username: "admin-1"
    email: "admin1@acme.io"
    clusters:
      - "worker-1"
      # - "worker-2"
    apiKeyValidity: "2025-12-31"
