projectname: "avesha"
workspaces:
  - name: "workspace-c"
    namespaces: 
      - "namespace-c2"
      - "namespace-c1"
    username: "admin-1"
    email: "admin1@acme.io"
    clusters:
      - "worker-1"
      # - "worker-2"
    validUntil: "2025-12-31"
