# Auto-GPR Test Configuration
# This configuration is designed to test auto-GPR functionality

# ==========================================
# Workspace Configuration
# ==========================================
workspace:
  name: "purple-test"
  clusters:
    - "worker-1"
  namespaces:
    - "purple-test"
  username: "test-user"
  email: "test@example.com"
  apiKeyValidity: "2024-12-31"

# ==========================================
# GPR Template Configurations
# ==========================================
# Templates will be created based on cluster inventory
gprTemplates:
  - name: "manual-gpr-tmpl-1"
    cluster: "worker-1"
    priority: 200
    exitDuration: "1h"
    numGpuNodes: 1
    enforceIdleTimeout: true
    idleTimeoutDuration: "30m"
    enableEviction: true
    requeueOnFailure: true

  - name: "manual-gpr-tmpl-2"
    cluster: "worker-1"
    priority: 150
    exitDuration: "30m"
    numGpuNodes: 1
    enforceIdleTimeout: true
    idleTimeoutDuration: "15m"
    enableEviction: true
    requeueOnFailure: true

# ==========================================
# Template Binding Configuration
# ==========================================
# This binds templates to the workspace
templateBinding:
  enableAutoGpr: true
  clusters:
    - clusterName: "worker-1"
      defaultTemplateName: "manual-gpr-tmpl-1"
      templates:
        - "manual-gpr-tmpl-1"
        - "manual-gpr-tmpl-2"

# ==========================================
# Test Configuration
# ==========================================
test:
  validateCreation: true
  validateTemplates: true
  validateBinding: true
  validateAutoGprDetection: true
  validateAutoGprStatus: true
  autoGprTimeoutSeconds: 900 # 15 minutes to wait for auto-GPRs
  gprVerificationTimeoutSeconds: 300 # 5 minutes to verify GPR status
  monitoringIntervalSeconds: 30

# ==========================================
# Advanced Configuration
# ==========================================
advanced:
  # Retry configuration
  retryAttempts: 3
  retryDelaySeconds: 5

  # Validation settings
  strictValidation: true
  validateInventory: true

  # GPR creation and verification
  validateGprStates: true
  expectedGprStates:
    - "Pending"
    - "Provisioning"
    - "Successful"

  # Output settings
  saveOutputs: true
  outputDirectory: "test_outputs"
  generateDetailedReport: true

# ==========================================
# Expected Behavior Documentation
# ==========================================
# This section documents the expected behavior for validation
expectedBehavior:
  templates:
    - "Templates created based on cluster inventory"
    - "Templates properly configured with GPU requirements"
    - "Templates accessible via EGS API"

  templateBinding:
    - "Binding created for workspace"
    - "Templates linked to workspace clusters"
    - "Auto-GPR capability enabled"

  autoGpr:
    - "Auto-GPRs created when workloads with GPU requests are deployed"
    - "Auto-GPRs use templates from the binding configuration"
    - "Auto-GPRs transition through expected states automatically"
    - "Auto-GPRs reach 'Successful' state when provisioned"

  inventoryManagement:
    - "GPU inventory tracked during GPR lifecycle"
    - "Inventory allocated when GPR is provisioned"
    - "Inventory state consistent with GPR status"
